import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  Modal,
  Dimensions
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import {
  AlertTriangle,
  Shield,
  Activity,
  Bell,
  Settings,
  RefreshCw,
  Eye,
  Lock,
  Smartphone,
  Wifi,
  Database,
  Users
} from 'lucide-react-native';
import SecurityBreachService from '@/services/security/SecurityBreachService';
import { formatRelativeTime } from '@/utils/formatRelativeTime';

const { width } = Dimensions.get('window');

interface SystemAlert {
  id: string;
  type: 'system' | 'network' | 'device' | 'user' | 'data';
  level: 'info' | 'warning' | 'critical';
  title: string;
  description: string;
  timestamp: number;
  source: string;
  resolved: boolean;
  autoGenerated: boolean;
}

const SecuritySystemAlerts: React.FC = () => {
  const [systemAlerts, setSystemAlerts] = useState<SystemAlert[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedAlert, setSelectedAlert] = useState<SystemAlert | null>(null);
  const [detailModalVisible, setDetailModalVisible] = useState(false);
  const [alertsEnabled, setAlertsEnabled] = useState(true);
  
  const breachService = SecurityBreachService.getInstance();

  useEffect(() => {
    generateSystemAlerts();
    const interval = setInterval(generateSystemAlerts, 60000); // Check every minute
    return () => clearInterval(interval);
  }, []);

  const generateSystemAlerts = async () => {
    if (!alertsEnabled) return;
    
    setLoading(true);
    try {
      // Simulate system monitoring alerts
      const mockAlerts: SystemAlert[] = [
        {
          id: `alert_${Date.now()}_1`,
          type: 'system',
          level: 'warning',
          title: 'High Memory Usage Detected',
          description: 'Application memory usage has exceeded 80% threshold. Consider optimizing memory allocation.',
          timestamp: Date.now() - 300000, // 5 minutes ago
          source: 'System Monitor',
          resolved: false,
          autoGenerated: true
        },
        {
          id: `alert_${Date.now()}_2`,
          type: 'network',
          level: 'critical',
          title: 'Suspicious Network Activity',
          description: 'Unusual outbound network traffic detected. Possible data exfiltration attempt.',
          timestamp: Date.now() - 600000, // 10 minutes ago
          source: 'Network Security',
          resolved: false,
          autoGenerated: true
        },
        {
          id: `alert_${Date.now()}_3`,
          type: 'device',
          level: 'info',
          title: 'Device Security Update Available',
          description: 'A new security update is available for your device. Update recommended.',
          timestamp: Date.now() - 1800000, // 30 minutes ago
          source: 'Device Manager',
          resolved: false,
          autoGenerated: true
        },
        {
          id: `alert_${Date.now()}_4`,
          type: 'user',
          level: 'warning',
          title: 'Multiple Failed Login Attempts',
          description: 'Detected 5 failed login attempts from IP 192.168.1.100 in the last 10 minutes.',
          timestamp: Date.now() - 900000, // 15 minutes ago
          source: 'Authentication System',
          resolved: false,
          autoGenerated: true
        },
        {
          id: `alert_${Date.now()}_5`,
          type: 'data',
          level: 'critical',
          title: 'Unauthorized Data Access Attempt',
          description: 'Attempt to access encrypted user data without proper authorization detected.',
          timestamp: Date.now() - 1200000, // 20 minutes ago
          source: 'Data Protection',
          resolved: false,
          autoGenerated: true
        }
      ];

      // Filter out resolved alerts and add new ones
      const existingIds = systemAlerts.map(a => a.id);
      const newAlerts = mockAlerts.filter(a => !existingIds.includes(a.id));
      
      if (newAlerts.length > 0) {
        setSystemAlerts(prev => [...newAlerts, ...prev].slice(0, 50)); // Keep only latest 50
        
        // Create security alerts for critical issues
        for (const alert of newAlerts.filter(a => a.level === 'critical')) {
          await breachService.createAlert({
            type: 'threat',
            priority: 'critical',
            title: alert.title,
            message: alert.description,
            actionRequired: true,
            category: 'system_security',
            actions: [
              {
                label: 'View Details',
                action: `system_alert_${alert.id}`
              },
              {
                label: 'Investigate',
                action: `investigate_${alert.id}`
              }
            ],
            metadata: { systemAlertId: alert.id, source: alert.source }
          });
        }
      }
    } catch (error) {
      console.error('Failed to generate system alerts:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleResolveAlert = (alertId: string) => {
    Alert.alert(
      'Resolve Alert',
      'Mark this system alert as resolved?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Resolve',
          onPress: () => {
            setSystemAlerts(prev => 
              prev.map(alert => 
                alert.id === alertId 
                  ? { ...alert, resolved: true }
                  : alert
              )
            );
          }
        }
      ]
    );
  };

  const handleInvestigate = async (alert: SystemAlert) => {
    // Simulate investigation process
    Alert.alert(
      'Investigation Started',
      `Starting automated investigation for: ${alert.title}\n\nThis will analyze logs, network traffic, and system behavior related to this alert.`,
      [
        { text: 'OK' },
        {
          text: 'View Progress',
          onPress: () => {
            // Could navigate to investigation dashboard
            console.log('Navigate to investigation dashboard');
          }
        }
      ]
    );
  };

  const getLevelColor = (level: SystemAlert['level']) => {
    switch (level) {
      case 'critical': return '#FF3B30';
      case 'warning': return '#FF9500';
      case 'info': return '#007AFF';
      default: return '#8E8E93';
    }
  };

  const getTypeIcon = (type: SystemAlert['type']) => {
    switch (type) {
      case 'system': return Activity;
      case 'network': return Wifi;
      case 'device': return Smartphone;
      case 'user': return Users;
      case 'data': return Database;
      default: return AlertTriangle;
    }
  };

  const renderAlertCard = (alert: SystemAlert) => {
    const IconComponent = getTypeIcon(alert.type);
    const levelColor = getLevelColor(alert.level);

    return (
      <TouchableOpacity
        key={alert.id}
        style={[
          styles.alertCard,
          { opacity: alert.resolved ? 0.6 : 1 }
        ]}
        onPress={() => {
          setSelectedAlert(alert);
          setDetailModalVisible(true);
        }}
      >
        <View style={styles.alertHeader}>
          <View style={[styles.alertIcon, { backgroundColor: `${levelColor}20` }]}>
            <IconComponent size={20} color={levelColor} />
          </View>
          
          <View style={styles.alertInfo}>
            <Text style={styles.alertTitle}>{alert.title}</Text>
            <Text style={styles.alertSource}>Source: {alert.source}</Text>
            <Text style={styles.alertTime}>{formatRelativeTime(alert.timestamp)}</Text>
          </View>
          
          <View style={[styles.levelBadge, { backgroundColor: levelColor }]}>
            <Text style={styles.levelText}>{alert.level.toUpperCase()}</Text>
          </View>
        </View>
        
        <Text style={styles.alertDescription} numberOfLines={2}>
          {alert.description}
        </Text>
        
        <View style={styles.alertActions}>
          {alert.resolved ? (
            <View style={styles.resolvedStatus}>
              <Shield size={16} color="#34C759" />
              <Text style={styles.resolvedText}>Resolved</Text>
            </View>
          ) : (
            <View style={styles.actionButtons}>
              <TouchableOpacity
                style={styles.investigateButton}
                onPress={() => handleInvestigate(alert)}
              >
                <Eye size={14} color="#007AFF" />
                <Text style={styles.investigateText}>Investigate</Text>
              </TouchableOpacity>
              
              <TouchableOpacity
                style={styles.resolveButton}
                onPress={() => handleResolveAlert(alert.id)}
              >
                <Text style={styles.resolveText}>Resolve</Text>
              </TouchableOpacity>
            </View>
          )}
        </View>
      </TouchableOpacity>
    );
  };

  const renderDetailModal = () => (
    <Modal
      visible={detailModalVisible}
      animationType="slide"
      presentationStyle="pageSheet"
    >
      <View style={styles.modalContainer}>
        <View style={styles.modalHeader}>
          <Text style={styles.modalTitle}>Alert Details</Text>
          <TouchableOpacity
            style={styles.closeButton}
            onPress={() => setDetailModalVisible(false)}
          >
            <Text style={styles.closeButtonText}>Close</Text>
          </TouchableOpacity>
        </View>
        
        {selectedAlert && (
          <ScrollView style={styles.modalContent}>
            <View style={styles.detailSection}>
              <Text style={styles.detailLabel}>Alert Type</Text>
              <Text style={styles.detailValue}>{selectedAlert.type.toUpperCase()}</Text>
            </View>
            
            <View style={styles.detailSection}>
              <Text style={styles.detailLabel}>Severity Level</Text>
              <View style={[
                styles.levelBadge,
                { backgroundColor: getLevelColor(selectedAlert.level) }
              ]}>
                <Text style={styles.levelText}>{selectedAlert.level.toUpperCase()}</Text>
              </View>
            </View>
            
            <View style={styles.detailSection}>
              <Text style={styles.detailLabel}>Description</Text>
              <Text style={styles.detailValue}>{selectedAlert.description}</Text>
            </View>
            
            <View style={styles.detailSection}>
              <Text style={styles.detailLabel}>Source System</Text>
              <Text style={styles.detailValue}>{selectedAlert.source}</Text>
            </View>
            
            <View style={styles.detailSection}>
              <Text style={styles.detailLabel}>Timestamp</Text>
              <Text style={styles.detailValue}>
                {new Date(selectedAlert.timestamp).toLocaleString()}
              </Text>
            </View>
            
            <View style={styles.detailSection}>
              <Text style={styles.detailLabel}>Auto-Generated</Text>
              <Text style={styles.detailValue}>
                {selectedAlert.autoGenerated ? 'Yes' : 'No'}
              </Text>
            </View>
            
            {!selectedAlert.resolved && (
              <View style={styles.modalActions}>
                <TouchableOpacity
                  style={styles.modalInvestigateButton}
                  onPress={() => {
                    handleInvestigate(selectedAlert);
                    setDetailModalVisible(false);
                  }}
                >
                  <Eye size={16} color="white" />
                  <Text style={styles.modalInvestigateText}>Start Investigation</Text>
                </TouchableOpacity>
                
                <TouchableOpacity
                  style={styles.modalResolveButton}
                  onPress={() => {
                    handleResolveAlert(selectedAlert.id);
                    setDetailModalVisible(false);
                  }}
                >
                  <Text style={styles.modalResolveText}>Mark as Resolved</Text>
                </TouchableOpacity>
              </View>
            )}
          </ScrollView>
        )}
      </View>
    </Modal>
  );

  const unresolvedCount = systemAlerts.filter(a => !a.resolved).length;
  const criticalCount = systemAlerts.filter(a => a.level === 'critical' && !a.resolved).length;

  return (
    <View style={styles.container}>
      {/* Header */}
      <LinearGradient
        colors={['#1C1C1E', '#2C2C2E']}
        style={styles.header}
      >
        <View style={styles.headerContent}>
          <View style={styles.headerLeft}>
            <AlertTriangle size={24} color="#FFFFFF" />
            <Text style={styles.headerTitle}>System Alerts</Text>
          </View>
          
          <View style={styles.headerRight}>
            <TouchableOpacity
              style={styles.refreshButton}
              onPress={generateSystemAlerts}
              disabled={loading}
            >
              <RefreshCw size={20} color="#FFFFFF" />
            </TouchableOpacity>
            
            <TouchableOpacity
              style={styles.settingsButton}
              onPress={() => setAlertsEnabled(!alertsEnabled)}
            >
              <Settings size={20} color={alertsEnabled ? '#34C759' : '#8E8E93'} />
            </TouchableOpacity>
          </View>
        </View>
        
        {/* Stats */}
        <View style={styles.statsContainer}>
          <View style={styles.statItem}>
            <Text style={styles.statValue}>{unresolvedCount}</Text>
            <Text style={styles.statLabel}>Unresolved</Text>
          </View>
          
          <View style={styles.statItem}>
            <Text style={[styles.statValue, { color: '#FF3B30' }]}>{criticalCount}</Text>
            <Text style={styles.statLabel}>Critical</Text>
          </View>
          
          <View style={styles.statItem}>
            <Text style={styles.statValue}>{systemAlerts.length}</Text>
            <Text style={styles.statLabel}>Total</Text>
          </View>
        </View>
      </LinearGradient>

      {/* Alerts List */}
      <ScrollView style={styles.alertsList}>
        {systemAlerts.length === 0 ? (
          <View style={styles.emptyState}>
            <Shield size={48} color="#8E8E93" />
            <Text style={styles.emptyTitle}>No System Alerts</Text>
            <Text style={styles.emptyMessage}>
              Your system is running smoothly. We'll notify you of any security concerns.
            </Text>
          </View>
        ) : (
          systemAlerts.map(renderAlertCard)
        )}
      </ScrollView>

      {renderDetailModal()}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F2F2F7'
  },
  header: {
    paddingTop: 16,
    paddingBottom: 20,
    paddingHorizontal: 16
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center'
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
    marginLeft: 12
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12
  },
  refreshButton: {
    padding: 8
  },
  settingsButton: {
    padding: 8
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around'
  },
  statItem: {
    alignItems: 'center'
  },
  statValue: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold'
  },
  statLabel: {
    color: '#FFFFFF',
    fontSize: 12,
    opacity: 0.8,
    marginTop: 4
  },
  alertsList: {
    flex: 1,
    padding: 16
  },
  alertCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12
  },
  alertHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12
  },
  alertIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12
  },
  alertInfo: {
    flex: 1
  },
  alertTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1C1C1E',
    marginBottom: 2
  },
  alertSource: {
    fontSize: 12,
    color: '#8E8E93',
    marginBottom: 2
  },
  alertTime: {
    fontSize: 12,
    color: '#8E8E93'
  },
  levelBadge: {
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4
  },
  levelText: {
    color: 'white',
    fontSize: 10,
    fontWeight: '600'
  },
  alertDescription: {
    fontSize: 14,
    color: '#8E8E93',
    lineHeight: 20,
    marginBottom: 12
  },
  alertActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end'
  },
  resolvedStatus: {
    flexDirection: 'row',
    alignItems: 'center'
  },
  resolvedText: {
    marginLeft: 4,
    fontSize: 14,
    color: '#34C759',
    fontWeight: '500'
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 8
  },
  investigateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#007AFF20',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6
  },
  investigateText: {
    marginLeft: 4,
    fontSize: 12,
    color: '#007AFF',
    fontWeight: '500'
  },
  resolveButton: {
    backgroundColor: '#34C759',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6
  },
  resolveText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600'
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1C1C1E',
    marginTop: 16,
    marginBottom: 8
  },
  emptyMessage: {
    fontSize: 14,
    color: '#8E8E93',
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 32
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'white'
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F7'
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1C1C1E'
  },
  closeButton: {
    padding: 4
  },
  closeButtonText: {
    fontSize: 16,
    color: '#007AFF'
  },
  modalContent: {
    flex: 1,
    padding: 16
  },
  detailSection: {
    marginBottom: 20
  },
  detailLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1C1C1E',
    marginBottom: 8
  },
  detailValue: {
    fontSize: 14,
    color: '#8E8E93',
    lineHeight: 20
  },
  modalActions: {
    gap: 12,
    marginTop: 20
  },
  modalInvestigateButton: {
    backgroundColor: '#007AFF',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center'
  },
  modalInvestigateText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8
  },
  modalResolveButton: {
    backgroundColor: '#34C759',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center'
  },
  modalResolveText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600'
  }
});

export default SecuritySystemAlerts;